formats:
    # format: {isOpen, hasSpec, isComputerReadable}
    # api:
    # asp:
    # atom:
    csv: [ true, true, true ]
    doc: [ false, true, true ]
    # gtfs:
    html: [ true, true, true ]
    # jpg:
    # json:
    # kmz:
    ods: [ false, true, true ]
    pdf: [ false, false, false ]
    # ppt:
    # rdf:
    # rss:
    # shp:
    # txt:
    wms: [ false, false, false ]
    wfs: [ false, false, false ]
    xls: [ false, true, true ]
    xml: [ true, true, true ]
    # zip: 
