parameters:
    licenses:
        'APIE':
            aliases:
                - 'Conditions générales de réutilisation des informations publiques (APIE)'
                - 'Licence Agence du Patrimoine Immatériel de l''État (Livraison successives de données)'
            authorship: true
            reuse: true
            redistribution: true
            commercial: false
        'BODACC':
            aliases:
                - 'Licence du BODACC'
            authorship: true
            reuse: true
            redistribution: true
            commercial: false
        'CCW/CROWN':
            aliases: []
            authorship: true
            reuse: true
            redistribution: true
            commercial: true
        'Data Publica':
            aliases:
                - 'Licence Data Publica'
            authorship: true
            reuse: true
            redistribution: true
            commercial: true
        'EuroStat':
            aliases:
                - 'Licence EuroStat'
            authorship: true
            reuse: true
            redistribution: true
            commercial: true
        'Française des Jeux':
            aliases:
                - 'Licence La Française des Jeux'
            authorship: true
            reuse: false
            redistribution: false
            commercial: false
        'GNU':
            aliases:
                - 'GNU General Public License v2'
            authorship: true
            reuse: true
            redistribution: true
            commercial: true
        'Information Publique':
            aliases:
                - 'Licence Information Publique'
            authorship: true
            reuse: true
            redistribution: true
            commercial: true
        'No Conditions':
            aliases:
                - 'No conditions apply'
                - 'None'
            authorship: true
            reuse: true
            redistribution: true
            commercial: true
        'Unknown':
            aliases:
                - 'Licence inconnue'
                - 'Use limitation'
                - 'Other'
            authorship: false
            reuse: false
            redistribution: false
            commercial: false
        'ODBL':
            aliases:
                - 'Licence ODBL Ville de Paris'
                - 'Licence ODBL'
                - 'Open Database License (ODbL)'
            authorship: true
            reuse: true
            redistribution: true
            commercial: true
        'OGL':
            aliases:
                - 'OKD Compliant'
            authorship: true
            reuse: true
            redistribution: true
            commercial: true
        'PDDL':
            aliases: []
            authorship: true
            reuse: true
            redistribution: true
            commercial: true
        'Public':
            aliases:
                - 'Public'
            authorship: true
            reuse: true
            redistribution: true
            commercial: true
        'Prix-Carburant':
            aliases:
                - 'Licence Prix-Carburant'
            authorship: true
            reuse: true
            redistribution: true
            commercial: true
        'UK Climate Projections':
            aliases:
                - 'UK Climate Projections Licence'
            authorship: true
            reuse: false
            redistribution: false
            commercial: false
        'licence ouverte / open licence':
            aliases: []
            authorship: true
            reuse: true
            redistribution: true
            commercial: true
