licenses:
      #equivalent  authorship reuse redistribution commercial

Licence Information Publique:  [Licence Information Publique, 1, 1, 1, 1]
Licence EuroStat: [EuroStat, -1, -1, -1, -1]
Licence La Française des Jeux: [Française des Jeux, 1, 0, 0, 0]
Licence ODBL Ville de Paris: [ODBL, 1, 1, 1, 1]
Licence Data Publica: [Licence Data Publica, 1, 1, 1, 1]
Licence ODBL: [ODBL, 1, 1, 1, 1]
ODBL : [ODBL, 1, 1, 1, 1]
PDDL : [PDDL, 1, 1, 1, 1]
Open Database License (ODbL): [ODBL, 1, 1, 1, 1]
Licence inconnue: [None, -1, -1, -1, -1]
Licence du BODACC: [BODACC, 1, 1, 1, -1]
Licence Prix-Carburant: [Prix-Carburant, 1, 1, 1, 1]
GNU General Public License v2: [GNU, 1, 1, 1, 1]
Public: [Public, 1, 1, 1, 1]
Licence Agence du Patrimoine Immatériel de l'État (Livraison successives de données): [APIE, 1, 1, 1, 1]
Conditions générales de réutilisation des informations publiques (APIE): [APIE, 1, 1, 1, 1]
CCW/CROWN: [CCW/CROWN 1, 1, 1, 1]
UK Climate Projections Licence: [UK Climate Projections Licence, 1, 0, 0, 0]
OKD Compliant: [OGL, 1, 1, 1, 1]
No conditions apply: [No Conditions, 1, 1, 1, 1]
Copyright (Copyright Forestry Commission Scotland): 
Use limitation: [None, -1, -1, -1, -1]
Other : [Other, -1, -1, -1, -1]


