# The arborescence of this file has 4 levels :
#  The category
#  sections of these catgories. Each section must have a "weight" attribute.
# This weight refers to the weight of the section in the category. Sections
# may have a "sections" attribute.
#  sections of these sections. Each subsection must have a "weight"
# attribute. A subsection may have a "subsections" attribute.
#  subsections of these sections. Each subsubsection must have a "weight"
# attribute.
# No more levels !

parameters:
    metrics:
        # Usability category
        usability:
            weight: 0.25
            description: "Usability"
            sections:
                 Search:
                    weight: 1
                    description: "Search"
                    sections:
                         search_engine_provided:
                            weight: 0.5
                            description: "A search engine is provided"
                         searchable_metadata:
                            weight: 0.25
                            description: "Metadata is searchable"
                         license_filtering:
                            weight: 0.25
                            description: "If the website offers several licences, the search engine has a sensible filtering option"

         # Cataloging category
        cataloging:
            weight: 0.25
            description: "Cataloging"
            sections:
                 identification:
                    description: "Identification"
                    weight: 0.2
                    sections:
                         person_in_charge:
                            weight: 1
                            description: "The identity and title of the person in charge is provided"

                 general:
                    weight: 0.60
                    description: "General Informations"
                    sections:
                         title_and_summary:
                            weight: 0.60
                            description: "There is at least a title and a summary"
                         category:
                            weight: 0.40
                            description: "There is a category"

                 temporal:
                    weight: 0.20
                    description: "Temporal Informations"
                    sections:
                         creation_date:
                            weight: 0.40
                            description: "There is a creation date"
                         update_date:
                            weight: 0.60
                            description: "There is an update date"
        # API category
        api:
            description: "API"
            weight: 0.25
            sections:
                 api_exists:
                    weight: 0.70
                    description: "There is an API"
                 api_documentation:
                    weight: 0.30
                    description: "There is documentation about how to access the data and interact with it"

        # Liveliness category
        liveliness:
            weight: 0.25
            description: "Liveliness"
            sections:
                User input:
                    description: "User input"
                    weight: 0.50
                    sections:
                         rating_possibility:
                            weight: 0.15
                            description: "The website offers ways of rating datasets"

                         feedback_channel:
                            weight: 0.15
                            description: "There is a possibility to comment for each data set"
                         suggest_dataset:
                            weight: 0.20
                            description: "Users can propose new datasets and also ask for existing ones to be made available"
                Information:
                    weight: 0.20
                    description: "Information"
                    sections:
                         opendata_explained:
                            weight: 1
                            description: "The OpenData concept is explained"
                Support Ressources:
                    weight: 0.30
                    description: "Links to support resources are present"
                    sections:
                       forum_section:
                           weight: 0.80
                           description: "There is a forum section"
                       contact_form_link:
                           weight: 0.20
                           description: "There is a link to a contact form"
