# The arborescence of this file has 4 levels :
#  The category
#  sections of these catgories. Each section must have a "weight" attribute.
# This weight refers to the weight of the section in the category. Sections
# may have a "sections" attribute.
#  sections of these sections. Each subsection must have a "weight"
# attribute. A subsection may have a "subsections" attribute.
#  subsections of these sections. Each subsubsection must have a "weight"
# attribute.
# No more levels !

parameters:
    metrics:
        # Usability category
        usability:
            weight: 1
            sections:
                 search:
                    weight: 1
                    sections:
                         search_engine_provided:
                            weight: 0.6

                         searchable_metadata:
                            weight: 0.25

                         license_filtering:
                            weight: 0.25

        # Cataloging category
        cataloging:
            weight: 1
            sections:
                 identification:
                    weight: 0.2
                    sections:
                         person_in_charge:
                            weight: 1

                 general:
                    weight: 0.60
                    sections:
                         title_and_summary:
                            weight: 0.60
                         category:
                            weight: 0.40

                 temporal:
                    weight: 0.20
                    sections:
                         creation_date:
                            weight: 0.40

                         update_date:
                            weight: 0.60

        # API category
        api:
            weight: 1
            sections:
                 api_exists:
                    weight: 0.70
                    
                 api_documentation:
                    weight: 0.30
                    
        # Liveliness category
        liveliness:
            weight: 1
            sections:
                 user_input:
                    weight: 0.80
                    sections:
                         rating_possibility:
                            weight: 0.15
                            
                         link_support_resources:
                            weight: 0.50
                            sections:
                                 forum_section:
                                    weight: 0.80
                                 contact_form_link:
                                    weight: 0.20
                         feedback_channel:
                            weight: 0.15
                            
                         suggest_dataset:
                            weight: 0.20
                            
                 information:
                    weight: 0.20
                    sections:
                         opendata_explained:
                            weight: 1
                            
