parameters:
    config.enabled_portals:
        - nantes
        - loire_atlantique
        - socrata
        - new_york
        - usa_gov
        - uk_gov
        - eu_gov
        - data_publica
        #- data_market

    # All the information we need for each platfom. Will be used to initialize the services
    portals.nantes:
        name:            "Nantes Open Data"
        base_url:        "http://data.nantes.fr/"
        api_url:         "http://data.nantes.fr/api/datastore_searchdatasets/1.0/39W9VSNCSASEOGV/?output=json"
        country:         "France"
        entity:          "City of Nantes"
        status:          "Institutional"
        search_engine:   true
        metadata_search: true
        filtering_license_search: false
        forum_section:   true
        contact_form: true
        rating_dataset: false   
        comment_dataset: false
        suggest_dataset: false
        api: true
        api_documentation: true
        opendata_concept_explained: true
        type: "inCité"

    portals.loire_atlantique:
        name:       "Loire Atlantique Open Data"
        base_url:   "http://data.loire-atlantique.fr/"
        api_url:    ""
        country:    "France"
        entity:     "Loire Atlantique General Council"
        status:     "Institutional"
        search_engine:   true
        metadata_search: true
        filtering_license_search: false
        forum_section:   true
        contact_form: true
        rating_dataset: false 
        comment_dataset: false
        suggest_dataset: false
        api: false
        api_documentation: false
        opendata_concept_explained: true
        type: "inCité"

    portals.socrata:
        name:       "Opendata by Socrata"
        base_url:   "https://opendata.socrata.com"
        api_url:    "https://opendata.socrata.com/api/views.json"
        country:    "USA"
        entity:     "Socrata"
        status:     "Private"
        search_engine:   true
        metadata_search: true
        filtering_license_search: false
        forum_section:   false
        contact_form: true
        rating_dataset: true
        comment_dataset: true
        suggest_dataset: true
        suggest_dataset: true
        api: true
        api_documentation: true
        opendata_concept_explained: false
        type: "Socrata"
    
    portals.new_york:
        name:       "NYC OpenData"
        base_url:   "https://nycopendata.socrata.com"
        api_url:    "https://nycopendata.socrata.com/api/views.json"
        country:    "USA"
        entity:     "City of New York"
        status:     "Institutional"
        search_engine:   true
        metadata_search: true
        filtering_license_search: false
        forum_section:   false
        contact_form: true
        rating_dataset: true
        comment_dataset: true
        suggest_dataset: true
        api: true
        api_documentation: true
        opendata_concept_explained: false
        type: "Socrata"

    portals.usa_gov:
        name:       "USA OpenData"
        base_url:   "https://explore.data.gov"
        api_url:    "https://explore.data.gov/api/views.json"
        country:    "USA"
        entity:     "United States Government"
        status:     "Institutional"
        search_engine:   true
        metadata_search: true
        filtering_license_search: false
        forum_section:   true
        contact_form: true
        rating_dataset: true
        comment_dataset: true
        suggest_dataset: true
        api: true
        api_documentation: true
        opendata_concept_explained: false
        type: "Socrata"

    portals.uk_gov:
        name:       "UK OpenData"
        base_url:   "http://data.gov.uk/dataset/"
        api_url:    "http://catalogue.data.gov.uk/api/rest/dataset"
        country:    "United Kingdom"
        entity:     "UK Government"
        status:     "Institutional"
        search_engine:   true
        metadata_search: true
        filtering_license_search: false
        forum_section:   true
        contact_form: true
        rating_dataset: true
        comment_dataset: true
        suggest_dataset: true
        api: true
        api_documentation: true
        opendata_concept_explained: false
        type: "CKAN"

    portals.eu_gov:
        name:       "Europe's Public Data"
        base_url:   "http://publicdata.eu/dataset/"
        api_url:    "http://publicdata.eu/api/rest/dataset"
        country:    "European Union"
        entity:     "European Linked Open Data Consortium"
        status:     "Private non-profit making"
        search_engine:   true
        metadata_search: true
        filtering_license_search: false
        forum_section:   false
        contact_form: true
        rating_dataset: false
        comment_dataset: false
        suggest_dataset: false
        api: true
        api_documentation: true
        opendata_concept_explained: false
        type: "CKAN"

    portals.data_publica:
        name:       "Data Publica"
        base_url:   "http://www.data-publica.com/"
        api_url:    ""
        country:    "France"
        entity:     "Data Publica"
        status:     "For profit"
        search_engine:   true
        metadata_search: true
        filtering_license_search: true
        forum_section:   false
        contact_form: true
        rating_dataset: false
        comment_dataset: true
        suggest_dataset: true
        api: true
        api_documentation: true
        opendata_concept_explained: true
        type: "Other"

    portals.data_market:
        name:       "DataMarket"
        base_url:   "http://datamarket.com/data/set/"
        api_url:    ""
        country:    "Iceland"
        entity:     "DataMarket"
        status:     "Private, For profit"
        search_engine:   true
        metadata_search: true
        #filtering_license_search: false
        #forum_section:   false
        #contact_form: true
        #rating_dataset: false
        #comment_dataset: false
        #suggest_dataset: false
        #api_documentation: false