homepage:
    pattern:    /
    defaults:   { _controller: App:Default:index }


portals:
    pattern:    /portals/{page_number}/{_format}
    defaults:   { _controller: App:Portal:index, page_number: 1, _format: html }
    requirements:
        _format: html|json

portal_details:
    pattern:    /portals/details/{portal_number}/{page_number}/{_format}
    defaults:   { _controller: App:Portal:details, page_number:1, _format: html }
    
delete_search_portal:
    pattern:    /detelesearchportal/{portal_id}
    defaults:   { _controller: App:Default:deleteSearchPortal, portal_id:1 }

dataset_details:
    pattern:    /datasets/details/{dataset_number}/{page_number}/{_format}
    defaults:   { _controller: App:Dataset:details, _format: html, page_number: 1 }