homepage:
    pattern:    /
    defaults:   { _controller: App:Default:index }

browser:
    pattern:    /browser
    defaults:   { _controller: App:Browser:index, _format: html }

portals:
    pattern:    /browser/portals/{_format}
    defaults:   { _controller: App:Portal:index, page_number: 1, _format: html }

portal_details:
    pattern:    /browser/portals/details/{portal_number}/{page_number}
    defaults:   { _controller: App:Portal:details, page_number:1, _format:html}

api_portal:
    pattern:    /api/portals/{page_index}/{page_size}
    defaults:   { _controller: App:Api:portals, page_index:0, page_size:10}
    requirements:
            limit:  \d+

api:
    pattern:    /api/{_format}
    defaults:   { _controller: App:Api:api, _format:json }
    


search:
    pattern:    /search
    defaults:   { _controller: App:Search:search, _format:html }

dataset_details:
    pattern:    /browser/datasets/details/{dataset_number}/{page_number}/{_format}
    defaults:   { _controller: App:Dataset:details, _format: html, page_number: 1 }

contact:
    pattern:  /contact
    defaults: { _controller: App:Default:contact }
