# put your application
# DIC parameters here
parameters:
    config.buzz.options:
        - "User-agent: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.1) Gecko/2008071615 Fedora/3.0.1-1.fc9 Firefox/3.0.1"
    config.buzz.timeout: 30

    config.file_dumper.data_path: "%kernel.project_root%/data/"

imports:
    # Import portals configuration
    - { resource: "portals.yml" }
    # Import categories
    - { resource: "categories.yml"}
    # Import formats
    - { resource: "formats.yml"}
    # Import licenses
    - { resource: "licenses.yml"}
    # Import metrics
    - { resource: "metrics.yml"}

# put your application
# service definitions here
services:
    # The request dispatcher service, used to fire concurrent requests
    request_dispatcher:
        class: Odalisk\Scraper\Tools\RequestDispatcher
        arguments:
            - %config.buzz.options%
            - %config.buzz.timeout%

    # A helper class to handle categories
    category_normalizer:
        class: Odalisk\Scraper\Tools\Normalize\CategoryNormalizer
        arguments:
            - @doctrine
            - %kernel.project_root%/logs/categories.log
        calls:
            - [ init, [ %categories% ] ]

    # A helper class to handle categories
    license_normalizer:
        class: Odalisk\Scraper\Tools\Normalize\LicenseNormalizer
        arguments:
            - @doctrine
            - %kernel.project_root%/logs/licenses.log
        calls:
            - [ init, [ %licenses% ] ]

    # A helper class to handle formats
    format_normalizer:
        class: Odalisk\Scraper\Tools\Normalize\FormatNormalizer
        arguments:
            - @doctrine
            - %kernel.project_root%/logs/formats.log
        calls:
            - [ init, [ %formats% ] ]
    # A helper class to handle dates
    date_normalizer:
        class: Odalisk\Scraper\Tools\Normalize\DateNormalizer
        arguments:
            - %kernel.project_root%/logs/dates.log

    # The various portals we want to analyse :
    # Base object for all our portals
    base_platform:
        class: Odalisk\Scraper\BasePortal
        abstract:  true
        calls:
            - [ setBuzz, [ @buzz, %config.buzz.timeout%, %config.buzz.options% ] ]
            - [ setDoctrine, [ @doctrine ] ]
            - [ setCategoryNormalizer, [@category_normalizer ] ]
            - [ setFormatNormalizer, [@format_normalizer ] ]
            - [ setDateNormalizer, [@date_normalizer ] ]
            - [ setLicenseNormalizer, [@license_normalizer ] ]

    # Base object for all portals using inCiteSolution
    base_inCiteSolution:
        class: Odalisk\Scraper\InCiteSolution\BaseInCiteSolutionPortal
        abstract:  true
        parent:  base_platform
    nantes:
        class: Odalisk\Scraper\InCiteSolution\Nantes\NantesPortal
        parent: base_inCiteSolution
        calls:
            - [ setConfiguration, [ "%portals.nantes%" ] ]
    loire_atlantique:
        class: Odalisk\Scraper\InCiteSolution\LoireAtlantique\LoireAtlantiquePortal
        parent: base_inCiteSolution
        calls:
            - [ setConfiguration, [ "%portals.loire_atlantique%" ] ]

    base_socrata:
        class: Odalisk\Scraper\Socrata\BaseSocrataPortal
        abstract:  true
        parent:  base_platform
    socrata:
        class: Odalisk\Scraper\Socrata\Socrata\SocrataPortal
        parent: base_socrata
        calls:
            - [ setConfiguration, [ "%portals.socrata%" ] ]
    new_york:
        class: Odalisk\Scraper\Socrata\NY\NewYorkPortal
        parent: base_socrata
        calls:
            - [ setConfiguration, [ "%portals.new_york%" ] ]
    usa_gov:
        class: Odalisk\Scraper\Socrata\USA\USAGovPortal
        parent: base_socrata
        calls:
            - [ setConfiguration, [ "%portals.usa_gov%" ] ]

    base_ckan:
        class: Odalisk\Scraper\CKAN\BaseCkanPortal
        abstract:  true
        parent:  base_platform
    uk_gov:
        class: Odalisk\Scraper\CKAN\UK\UKGovPortal
        parent: base_ckan
        calls:
            - [ setConfiguration, [ "%portals.uk_gov%" ] ]
    eu_gov:
        class: Odalisk\Scraper\CKAN\DataEU\EUPortal
        parent: base_ckan
        calls:
            - [ setConfiguration, [ "%portals.eu_gov%" ] ]

    data_publica:
        class: Odalisk\Scraper\DataPublica\DataPublicaPortal
        parent:  base_platform
        calls:
            - [ setConfiguration, [ "%portals.data_publica%" ] ]

    data_market:
        class: Odalisk\Scraper\DataMarket\DataMarketPortal
        parent: base_platform
        calls:
            - [ setConfiguration, [ "%portals.data_market%" ] ]

    base_lrnrln:
        class: Odalisk\Scraper\LrnRln\BaseLrnRln
        abstract: true
        parent: base_platform
    montpellier:
        class: Odalisk\Scraper\LrnRln\Montpellier\MontpellierPortal
        parent: base_lrnrln
        calls:
            - [ setConfiguration, [ "%portals.montpellier%" ] ]
