# put your application
# DIC parameters here
parameters:
    buzz_options:
        - "User-agent: %app.user_agent%"
    buzz_timout: 30 # Timeout for the requests
    
    request_dispatcher.class: Odalisk\Scraper\Tools\RequestDispatcher
    request_dispatcher.timeout: 10
    
    base_platform.class: Odalisk\Scraper\BasePlatform

# put your application
# service definitions here
services:
    request_dispatcher:
        class: %request_dispatcher.class%
        arguments:
            - %buzz_options%
            - %request_dispatcher.timeout%
    base_platform:
        class: %base_platform.class%
        abstract:  true
        calls:
            - [ setBuzz, [ @buzz, %buzz_timout% ] ]
            - [ setBuzzOptions, [ %buzz_options% ] ]
            - [ setDoctrine, [ @doctrine ] ]
    uk_platform:
        class: Odalisk\Scraper\UK\UkPlatform
        parent: base_platform
        calls:
            - [ setName, [ "data.gov.uk" ] ]
            - [ setBaseUrl, [ "http://data.gov.uk/dataset/" ] ]
            - [ setApiUrl, [ "http://catalogue.data.gov.uk/api/rest/dataset" ] ]
    base_inCiteSolution:
        class: Odalisk\Scraper\InCiteSolution\BaseInCiteSolution
        abstract:  true
        parent:  base_platform

    nantes_platform:
        class: Odalisk\Scraper\InCiteSolution\Nantes\NantesPlatform
        parent: base_inCiteSolution
        calls:
            - [ setName, [ "data.nantes.fr" ] ]         
            - [ setBaseUrl, [ "http://data.nantes.fr/donnees/detail/" ] ]
            - [ setApiUrl, [ "http://data.nantes.fr/api/datastore_searchdatasets/1.0/39W9VSNCSASEOGV/?output=json" ] ]
    loire_atlantique_platform:
        class: Odalisk\Scraper\InCiteSolution\LoireAtlantique\LoireAtlantiquePlatform
        parent: base_inCiteSolution
        calls:
            - [ setName, [ "data.loire-atlantique.fr" ] ]         
            - [ setBaseUrl, [ "http://data.loire-atlantique.fr/donnees/detail/" ] ]       
