# put your application
# DIC parameters here
parameters:
    buzz_options:
        - "User-agent: %app.user_agent%"
    buzz_timout: 30 # Timeout for the requests
    
    request_dispatcher.class: Odalisk\Scraper\Tools\RequestDispatcher
    request_dispatcher.timeout: 10
    
    base_platform.class: Odalisk\Scraper\BasePlatform

# put your application
# service definitions here
services:
    request_dispatcher:
        class: %request_dispatcher.class%
        arguments:
            - %buzz_options%
            - %request_dispatcher.timeout%
    base_platform:
        class: %base_platform.class%
        abstract:  true
        calls:
            - [ setBuzz, [ @buzz, %buzz_timout% ] ]
            - [ setBuzzOptions, [ %buzz_options% ] ]
            - [ setDoctrine, [ @doctrine ] ]
    base_inCiteSolution:
        class: Odalisk\Scraper\InCiteSolution\BaseInCiteSolution
        abstract:  true
        parent:  base_platform

    nantes_platform:
        class: Odalisk\Scraper\InCiteSolution\Nantes\NantesPlatform
        parent: base_inCiteSolution
        calls:
            - [ setName, [ "data.nantes.fr" ] ]         
            - [ setBaseUrl, [ "http://data.nantes.fr/donnees/detail/" ] ]
            - [ setApiUrl, [ "http://data.nantes.fr/api/datastore_searchdatasets/1.0/39W9VSNCSASEOGV/?output=json" ] ]
    loire_atlantique_platform:
        class: Odalisk\Scraper\InCiteSolution\LoireAtlantique\LoireAtlantiquePlatform
        parent: base_inCiteSolution
        calls:
            - [ setName, [ "data.loire-atlantique.fr" ] ]         
            - [ setBaseUrl, [ "http://data.loire-atlantique.fr/donnees/detail/" ] ]       

    base_socrata:
        class: Odalisk\Scraper\Socrata\BaseSocrata
        abstract:  true
        parent:  base_platform
    socrata_platform:
        class: Odalisk\Scraper\Socrata\Socrata\SocrataPlatform
        parent: base_socrata
        calls:
            - [ setName, [ "opendata.socrata.com" ] ]         
            - [ setBaseUrl, ["https://opendata.socrata.com/d/"] ]
            - [ setApiUrl, [ "https://opendata.socrata.com/api/views.json" ] ]
    ny_platform:
        class: Odalisk\Scraper\Socrata\NY\NYPlatform
        parent: base_socrata
        calls:
            - [ setName, [ "nycopendata.socrata.com" ] ]         
            - [ setBaseUrl, ["https://nycopendata.socrata.com/d/"] ]
            - [ setApiUrl, [ "https://nycopendata.socrata.com/api/views.json" ] ]
    usa_gov_platform:
        class: Odalisk\Scraper\Socrata\USA\USAGovPlatform
        parent: base_socrata
        calls:
            - [ setName, [ "www.data.gov" ] ]         
            - [ setBaseUrl, ["https://explore.data.gov/d/"] ]
            - [ setApiUrl, [ "https://explore.data.gov/api/views.json" ] ]

    base_ckan:
        class: Odalisk\Scraper\CKAN\BaseCKAN
        abstract:  true
        parent:  base_platform
    uk_platform:
        class: Odalisk\Scraper\CKAN\UK\UKPlatform
        parent: base_ckan
        calls:
            - [ setName, [ "data.gov.uk" ] ]
            - [ setBaseUrl, [ "http://data.gov.uk/dataset/" ] ]
            - [ setApiUrl, [ "http://catalogue.data.gov.uk/api/rest/dataset" ] ]
    data_eu_platform:
        class: Odalisk\Scraper\CKAN\DataEU\DataEUPlatform
        parent: base_ckan
        calls:
            - [ setName, [ "publicdata.eu" ] ]
            - [ setBaseUrl, [ "http://publicdata.eu/dataset/" ] ]
            - [ setApiUrl, [ "http://publicdata.eu/api/rest/dataset" ] ]
<<<<<<< HEAD

    data_publica_platform:
        class: Odalisk\Scraper\DataPublica\DataPublicaPlatform
        parent:  base_platform
        calls:
            - [ setName, [ "data-publica.com" ] ]

=======
>>>>>>> 365ae6735bfb26ff75f8910d72578cd890f4c3c3
