<?php

namespace Odalisk\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatasetCriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatasetCriteriaRepository extends EntityRepository
{

    private $criteria;
    private $dataset;

    public function init() {
        $this->criteria = array();
    }

    public function clear() {
        $sth = $this->getEntityManager()
            ->getConnection()
            ->prepare('TRUNCATE TABLE dataset_criteria')
            ->execute();
    }

    public function getCriteria($dataset) {
        $this->dataset = $dataset;

        $this->getGeneralCriteria();
        $this->getLicenseCriteria();
        $this->getFormatCriteria();

        return($this->criteria);
    }

    public function getGeneralCriteria() {
        $d = $this->dataset;

        $this->criteria['setIsTitleAndSummary'] = ($d->getName() && $d->getSummary());
        $this->criteria['setIsOwner'] = $d->getOwner() != NULL;
        $this->criteria['setIsProvider'] = ($d->getProvider() || $d->getOwner());
        $this->criteria['setIsLastUpdateOn'] = $d->getLastUpdatedOn() != NULL;
        $this->criteria['setIsMaintainer'] = $d->getMaintainer() != NULL;
        $this->criteria['setIsReleasedOn'] = $d->getReleasedOn() != NULL;
    }

    public function getLicenseCriteria() {
        $license = $this->dataset->getLicense();
        if($license) {
            $this->criteria['setIsGoodLicense']  = $license->isGoodLicense();
            $this->criteria['setLicenseQuality'] = $license->getQuality();
        } else {
            $this->criteria['setIsGoodLicense']  = 0;
            $this->criteria['setLicenseQuality'] = 0;
        }
    }

    public function getFormatCriteria() {
        $formats = $this->dataset->getFormats();
        foreach($formats as $format) {
            if($format->isGood()) {
                $this->criteria['setIsAtLeastOneGoodFormat'] = true;
                return;
            }
        }

        $this->criteria['setIsAtLeastOneGoodFormat'] = false;
    }

    public function getPortalAverages($portalId) {
        $sth = $this->getEntityManager()
            ->getConnection()
            ->prepare('
                    SELECT
                        (SUM(is_title_and_summary) / COUNT(*)) as title,
                        (SUM(is_released_on) / COUNT(*)) as released_on,
                        (SUM(is_last_update_on) / COUNT(*)) as last_update_on,
                        (SUM(is_provider) / COUNT(*)) as provider,
                        (SUM(is_owner) / COUNT(*)) as owner,
                        (SUM(is_maintainer) / COUNT(*)) as maintainer,
                        (SUM(is_good_license) / COUNT(*)) as good_license,
                        (SUM(license_quality) / COUNT(*)) as license_quality,
                        (SUM(is_at_least_one_good_format) / COUNT(*)) as at_least_one_good_format
                    FROM dataset_criteria JOIN datasets ON dataset_criteria.id = datasets.criteria
                    WHERE datasets.portal_id = :portal_id
            ');
        $sth->execute(array('portal_id' => $portalId));

        return($sth->fetch(\PDO::FETCH_ASSOC));
    }

}
