<?php

namespace Odalisk\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatasetCriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatasetCriteriaRepository extends EntityRepository
{

    private $criteria;
    private $dataset;

    public function init() {
        $this->criteria = array();
    }

    public function getCriteria($dataset) {
        $this->dataset = $dataset;

        $this->getGeneralCriteria();
        $this->getLicenseCriteria();
        $this->getFormatCriteria();

        return($this->criteria);
    }

    public function getGeneralCriteria() {
        $d = $this->dataset;

        $this->criteria['setIsTitleAndSummary'] = ($d->getName() && $d->getSummary());
        $this->criteria['setIsOwner'] = $d->getOwner() != NULL;
        $this->criteria['setIsProvider'] = ($d->getProvider() && $d->getOwner());
        $this->criteria['setIsLastUpdateOn'] = $d->getLastUpdatedOn() != NULL;
        $this->criteria['setIsMaintainer'] = $d->getMaintainer() != NULL;
        $this->criteria['setIsReleasedOn'] = $d->getReleasedOn() != NULL;
    }

    public function getLicenseCriteria() {
        $license = $this->dataset->getLicense();
        if($license) {
            $this->criteria['setIsGoodLicense']  = $license->isGoodLicense();
            $this->criteria['setLicenseQuality'] = $license->getQuality();
        } else {
            $this->criteria['setIsGoodLicense']  = 0;
            $this->criteria['setLicenseQuality'] = 0;
        }
    }

    public function getFormatCriteria() {
        $formats = $this->dataset->getFormats();
        foreach($formats as $format) {
            if($format->isGood()) {
                $this->criteria['setIsAtLeastOneGoodFormat'] = true;
                return;
            }
        }

        $this->criteria['setIsAtLeastOneGoodFormat'] = false;
    }
}
