<?php

namespace Odalisk\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatRepository extends EntityRepository
{
}