<?php

namespace Odalisk\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MetricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetricRepository extends EntityRepository
{

}