<?php

namespace Odalisk\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PortalCriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortalCriteriaRepository extends EntityRepository
{
}