<?php

namespace Odalisk\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PortalCriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortalCriteriaRepository extends EntityRepository
{
    public function getPortalCriteria($portal) {
        $sth = $this->getEntityManager()
            ->getConnection()
            ->prepare('
SELECT 
                        `opendata_concept_explained` as opendata_explained,
                        `api_documentation` as api_documentation,
                        `api` as api_exists,
                        `comment_dataset` as feedback_channel,
                        `suggest_dataset` as suggest_dataset,
                        `rating_dataset` as rating_possibility,
                        `contact_form` as contact_form_link,
                        `forum_section` as forum_section,
                        `filtering_license_search` as license_filtering,
                        `metadata_search` as searchable_metadata,
                        `search_engine` as search_engine_provided
                         FROM `portal_criteria` WHERE id IN (SELECT `criteria_id` FROM portals WHERE id = :portal_id);
            ');
        $sth->execute(array('portal_id' => $portal->getId()));
        return($sth->fetch(\PDO::FETCH_ASSOC));
    }
}
