<?php

namespace Odalisk\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StatisticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticsRepository extends EntityRepository
{
}
