
# All your application-wide configuration should live here.
# Every parameter here will be automatically transformed into
# an "app.%s" parameter inside the service container.

all:
    maintenance: false
    user_agent: "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.1) Gecko/2008071615 Fedora/3.0.1-1.fc9 Firefox/3.0.1"
    platforms: # Name of the services defined in service.yml
        - uk_platform
        - data_eu_platform
        - nantes_platform
        - loire_atlantique_platform
        - socrata_platform
        - ny_platform
        - usa_gov_platform
prod: ~
dev:  ~
test: ~
